### PR TITLE
251: Weird cropping of M+ dungeon names

### PR DESCRIPTION
**Pull request by jhwess**
* Adds css selector for child divs of .videoButton to show overflowing text as ellipsis.

### CODE REVIEW

**Comment by jhwess** [comment]
image

**Comment by aza547** [comment]
Thanks for this - it's great to have more people involved! 

A few thoughts: 
- Should remove code at ~335 in videoButton.tsx that slices the string as no longer required, that was my initial attempts to make this work.

- Can we apply the same thing to character names? I think they could be a little too long also. Think the issue had an example.

- Any other fields worth worrying about? Can't think of any off the top of my head.

- Worth including a changelog entry too as this is a user facing change.

Hopefully formatting isn't too garbled as I'm on mobile. Cheers!

**Comment by jhwess** [comment]
No problem, hyped to help out!
* will do
* These changes already apply the styling to any div that is a child of any element with the "videoButton" class which should cover any other potentially-problematic fields here.
  * Tested this with player names by manually editing the html with the dev tools:
image
* Ah yeah I'll do that as well with the next commit

If we wanted to use a css preprocessor, we could extract this into a re-usable set of styles (IIRC they're called mixins in SCSS) because it's a pretty common use case.

**Comment by jhwess** [comment]
Addressed PR feedback and resolved conflicts

**Comment by aza547** [comment]
> No problem, hyped to help out!
> 
> * will do
> * These changes already apply the styling to any div that is a child of any element with the "videoButton" class which should cover any other potentially-problematic fields here.

Ah - duh - great, my mistake! 

>   
>   * Tested this with player names by manually editing the html with the dev tools:
>     image
> * Ah yeah I'll do that as well with the next commit

Looks great!

> 
> If we wanted to use a css preprocessor, we could extract this into a re-usable set of styles (IIRC they're called mixins in SCSS) because it's a pretty common use case.

Not something I've ever heard of - but keen to be educated :)

**Pull request merged**
