### PR TITLE
Feature: Raid instance difficulty

### LINKED ISSUE #53: Show difficulty for raid videos
Pretty easy one. Indicator for the difficulty, e.g. LFR / normal / heroic / mythic.

Think it's included in https://wowpedia.fandom.com/wiki/ENCOUNTER_END, see difficultyID.

We read this in logutils.ts, `handleRaidStopLine()`.

- First step is to write this to the metadata json file.
- Second is to display it in the UI

### PR DESCRIPTION
**Pull request by tdaugaard**
Closes #53. As the title says, introduces the saving and display of the difficulty for raids.

There isn't much space left on the VideoButton, but I managed to fit it in.

### CODE REVIEW

**Comment by aza547** [comment]
Had a test, didn't work for the raid.py test script.

Got a `  "difficultyID": null,` in the json.

**Comment by aza547** [comment]
Hah this might actually be the bug you are fixing with the rewrite of splitLogLine in the M+ PR. I think it's due to the raid.py using "Lihuvim, Principal Architect" as the encounter - the comma is causing split problems.

**Comment by aza547** [comment]
Sure enough, removed the comment and looks good. Haven't reviewed the code yet, will do today with a bit of luck.

**Comment by tdaugaard** [comment]
> Hah this might actually be the bug you are fixing with the rewrite of splitLogLine in the M+ PR. I think it's due to the raid.py using "Lihuvim, Principal Architect" as the encounter - the comma is causing split problems.

Oh, right! I _could_ split the changes to `splitLogLine()` from the M+ feature to a separate branch/PR if you want. It'll probably take a bit more testing and debugging to get the M+ feature right.

**Comment by tdaugaard** [comment]
Should merge #95  before this one.

**Comment by aza547** [comment]
Think this is ready now #95 is in. Merging.

**Pull request merged**
